# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.0'

gem 'pry'
gem 'pry-byebug'
gem "grape", "~> 2.0.0"

gem 'byebug', platforms: %i[mri mingw x64_mingw]
gem 'rack-test'
gem 'rspec', '~> 3.3.0'
gem 'lobanov', path: '../..'
