# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

gem 'rails', '~> 6.1.4', '>= 6.1.4.2'
gem 'puma', '~> 5.0'
gem 'pry'
gem 'pry-byebug'

gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
gem 'rspec-rails', '5.1.0'
# gem 'lobanov', github: 'spajic/lobanov'
gem 'lobanov', path: '/Users/spajic/code/lobanov'
