# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.5'

gem 'pry'
gem 'pry-byebug'
gem 'puma', '~> 5.0'
gem 'rails', '~> 6.1.4', '>= 6.1.4.2'

gem 'byebug', platforms: %i[mri mingw x64_mingw]
gem 'rspec-rails', '5.1.0'
gem 'lobanov', path: '../..'
