Feature: generate schema for test with :lobanov tag
  When you write rspec test with :lobanov tag it generates schema

  Scenario: basic usage
    When I cd to "../../test_apps/rails_61"

    Given a file named "spec/controllers/fruits_controller_spec.rb" with:
      """ruby
      require 'rails_helper'

      RSpec.describe FruitsController, type: :controller do
        describe 'GET #index' do
          it 'returns a success response', :lobanov do
            get :index
            expect(response).to have_http_status(:ok)
            expect(json_body).to eq({fruits: 'will_be_here'})
          end
        end
      end
      """

    When I run `rspec spec/controllers/fruits_controller_spec.rb`
    Then the example should pass

  # Then a file named "spec/murker/v1/martians/GET.yml" should exist

  # Then the file "spec/murker/v1/martians/GET.yml" should contain:
  # """yml
  # ---
  # openapi: 3.0.0
  # info:
  #   title: Generated by Murker
  #   version: 0.1.0
  # paths:
  #   "/v1/martians":
  #     get:
  #       responses:
  #         "'200'":
  #           description: GET /v1/martians -> 200
  #           content:
  #             application/json:
  #               schema:
  #                 type: array
  #                 minItems: 1
  #                 uniqueItems: true
  #                 items:
  #                   type: object
  #                   required:
  #                   - id
  #                   - name
  #                   - age
  #                   properties:
  #                     id:
  #                       type: integer
  #                     name:
  #                       type: string
  #                     age:
  #                       type: integer
  # """
